name: Deploy Development Environment
on:
  workflow_dispatch:
#  push:
#    branches:
#      - main

permissions:
  contents: read
  id-token: write
  pull-requests: write
  actions: read
  security-events: write

jobs:
  code-tests:
    name: Code Quality and Security Tests
    uses: ./.github/workflows/code-tests.yml

  infra-plan:
    needs: code-tests
    name: Terraform Plan
    uses: ./.github/workflows/infra-plan.yml

  approve-dev:
    needs: infra-plan
    name: Approve Dev Deployment
    runs-on: ubuntu-latest
    environment: dev-approval
    steps:
      - name: approval
        run: echo "Dev deployment approved. Continuing with infra apply, build and deploy."

  infra-apply:
    needs: approve-dev
    name: Terraform Apply
    uses: ./.github/workflows/infra-apply.yml
    
  app-build:
    needs: infra-apply
    name: Build and Push Application
    uses: ./.github/workflows/app-build.yml

  app-deploy:
    needs: app-build
    name: Deploy Application
    uses: ./.github/workflows/app-deploy.yml
    with:
      image-tag: ${{ needs.app-build.outputs.image-tag }}